import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [
  //   {
  //     type: 'autogenerated', 
  //     dirName: '.',
  //   },
  // ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  // 教程
  guideSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'guide',
    }
  ],
  // API 参考
  apiSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'api',
    }
  ],
  // 场景用例
  casesSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'examples',
    }
  ],

  taroSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'taro',
    }
  ],
  reactNativeSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'react-native',
    }
  ],
  electronSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'electron',
    }
  ],
  nextSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'next',
    }
  ],
  olSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'openlayers',
    }
  ],

  componentsSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'components',
    }
  ],

  // 前端基石
  basicSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'basics',
    }
  ],

  // Docusaurus 教程
  tutorialSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'tutorial',
    },
  ],

};

export default sidebars;
